Доверстать главную страницу
htmlacademy-adaptive/298063-pink-21 pull request #11
Opened 2020-12-28 11:03 UTC by dardorsh

2020-12-29 21:41 UTC, kosovych requested changes

2020-12-29 21:41 UTC, kosovych commented on source/index.html
![image](https://user-images.githubusercontent.com/19348382/103315017-0b63b680-4a2d-11eb-9a3d-b8aeacf52215.png)
из-за этого отступа поехала вся верстка

2020-12-29 21:41 UTC, kosovych commented on source/index.html
![image](https://user-images.githubusercontent.com/19348382/103315059-31895680-4a2d-11eb-9e16-625651a6a378.png)

2020-12-29 21:41 UTC, kosovych commented on source/index.html
![image](https://user-images.githubusercontent.com/19348382/103315263-ba07f700-4a2d-11eb-91ef-f1f73e1d32c9.png)

2020-12-29 21:41 UTC, kosovych commented on source/index.html
тоже самое на планшете

2020-12-29 21:41 UTC, kosovych commented on source/index.html
>        <nav class="main-nav main-nav--closed main-nav--nojs">
![image](https://user-images.githubusercontent.com/19348382/103315322-e4f24b00-4a2d-11eb-99b5-39cfabcb4e57.png)

2020-12-29 21:41 UTC, kosovych commented on source/index.html
> +            <button class="slider__button slider__button--previous" type="button" aria-label="К предыдущему слайду">
добавь интерактивности (см. стайлгайд)

2020-12-29 21:41 UTC, kosovych commented on source/index.html
>          </div>
это все одна ссылка + добавь интерактивности

2020-12-29 21:41 UTC, kosovych commented on source/index.html
'.impact__link' должна иметь такую же интерактивность как и другие такие-то ссылки

2020-12-29 21:41 UTC, kosovych commented on source/index.html
> +            <a class="slider__toggle" aria-label="Третий слайд"></a>
сверь все состояния со стайлгайдом

2020-12-29 21:41 UTC, kosovych commented on source/index.html
> +                    <span class="prices-table__item--yes">Есть</span>
модификаторы без элементов

2021-01-02 10:22 UTC, dardorsh commented on source/index.html
fixed

2021-01-02 10:22 UTC, dardorsh commented on source/index.html
+

2021-01-02 10:23 UTC, dardorsh commented on source/index.html
fixed

2021-01-02 10:23 UTC, dardorsh commented on source/index.html
fixed

2021-01-02 10:23 UTC, dardorsh commented on source/index.html
>        <nav class="main-nav main-nav--closed main-nav--nojs">
fixed

2021-01-02 10:33 UTC, dardorsh commented on source/index.html
> +            <button class="slider__button slider__button--previous" type="button" aria-label="К предыдущему слайду">
done

2021-01-02 10:44 UTC, dardorsh commented on source/index.html
fixed

2021-01-02 11:07 UTC, dardorsh commented on source/index.html
>          </div>
fixed

2021-01-02 11:33 UTC, dardorsh commented on source/index.html
> +            <a class="slider__toggle" aria-label="Третий слайд"></a>
fixed

2021-01-02 13:37 UTC, dardorsh commented on source/index.html
> +                    <span class="prices-table__item--yes">Есть</span>
fixed

2021-01-08 19:59 UTC, kosovych requested changes

2021-01-08 19:59 UTC, kosovych commented on source/index.html
![image](https://user-images.githubusercontent.com/19348382/104057842-79f9fe80-51fb-11eb-9dc5-27502f05917d.png)
появляется скролл на 660px

2021-01-08 19:59 UTC, kosovych commented on source/index.html
>            <span class="advantages__title--bottom">Нам есть, что вам <br> предложить!</span>
advantages__title--top advantages__title--bottom модификаторы без блоков

2021-01-08 19:59 UTC, kosovych commented on source/index.html
>          <div class="advantanges__wrapper">
опечатка. advantages__wrapper*

2021-01-09 16:19 UTC, dardorsh commented on source/index.html
fixed

2021-01-09 17:24 UTC, dardorsh commented on source/index.html
>            <span class="advantages__title--bottom">Нам есть, что вам <br> предложить!</span>
fixed

2021-01-09 17:25 UTC, dardorsh commented on source/index.html
>          <div class="advantanges__wrapper">
fixed

2021-01-09 22:40 UTC, merged