Добавляет финальную верстку страницы формы
htmlacademy-adaptive/298063-pink-21 pull request #12
Opened 2021-01-10 12:26 UTC by dardorsh

2021-01-10 22:31 UTC, kosovych requested changes

2021-01-10 22:31 UTC, kosovych commented on source/sass/blocks/page-header.scss
>    @media (min-width: $tablet-width) {
![image](https://user-images.githubusercontent.com/19348382/104137010-6b018080-53a2-11eb-9a04-52c0e0c64cda.png)
PP

2021-01-10 22:31 UTC, kosovych commented on source/sass/blocks/page-header.scss
>    @media (min-width: $tablet-width) {
![image](https://user-images.githubusercontent.com/19348382/104137108-3215db80-53a3-11eb-94f0-b70ca64b142c.png)
убери иконки на мобилке

2021-01-10 22:31 UTC, kosovych commented on source/sass/blocks/page-header.scss
>    @media (min-width: $tablet-width) {
на счет user-name__label я бы сделал отдельный БЭМ блок для текстовых инпутов 
```
div.input
    label.input__label
    input.input__filed
```

тот же блок можно использовать для номара телефона и почты только разширить его модификатором

2021-01-10 22:31 UTC, kosovych commented on source/sass/blocks/page-header.scss
>    @media (min-width: $tablet-width) {
тоже самое для чекбоксов и радио

2021-01-10 22:31 UTC, kosovych commented on source/sass/blocks/page-header.scss
>      background-image: url("../../img/bg-back-tablet@1x.jpg");
добавь disabled состояния для чекбоксов и радио

2021-01-11 17:27 UTC, dardorsh commented on source/sass/blocks/page-header.scss
>    @media (min-width: $tablet-width) {
fixed

2021-01-11 17:49 UTC, dardorsh commented on source/sass/blocks/page-header.scss
>    @media (min-width: $tablet-width) {
fixed

2021-01-11 18:07 UTC, dardorsh commented on source/sass/blocks/page-header.scss
>      background-image: url("../../img/bg-back-tablet@1x.jpg");
done

2021-01-11 19:07 UTC, kosovych commented on source/sass/blocks/page-header.scss
>      background-image: url("../../img/bg-back-tablet@1x.jpg");
![image](https://user-images.githubusercontent.com/19348382/104226682-e3bf1600-5450-11eb-94d8-94736ed0e63b.png)
disabled чекбокс реагирует на наведение. нужно убрать

2021-01-11 19:07 UTC, kosovych commented on source/sass/blocks/page-header.scss
>    @media (min-width: $tablet-width) {
решила не менять?

2021-01-11 19:08 UTC, kosovych commented on source/sass/blocks/page-header.scss
>      background-image: url("../../img/bg-back-tablet@1x.jpg");
тоже самое с радио

2021-01-12 18:28 UTC, dardorsh commented on source/sass/blocks/page-header.scss
>      background-image: url("../../img/bg-back-tablet@1x.jpg");
fixed

2021-01-12 20:18 UTC, dardorsh commented on source/sass/blocks/page-header.scss
>    @media (min-width: $tablet-width) {
добавила отдельные блоки

2021-01-12 21:28 UTC, merged