Доверстать страницу каталога
htmlacademy-adaptive/298063-pink-21 pull request #13
Opened 2021-01-13 10:42 UTC by dardorsh

2021-01-13 19:50 UTC, kosovych requested changes

2021-01-13 19:50 UTC, kosovych commented on source/catalog.html
>                    <div class="filter-setup__wrapper">
добавь указатели для активной страницы site-nav__link

2021-01-13 19:50 UTC, kosovych commented on source/catalog.html
>                        <div class="range-controls">
page-footer__copyright copyright это все ссылка

2021-01-13 19:50 UTC, kosovych commented on source/catalog.html
>                      <div class="filter-setup__option">
.filter-setup__item добавь type для кнопок

2021-01-14 07:04 UTC, dardorsh commented on source/catalog.html
>                      <div class="filter-setup__option">
done

2021-01-14 07:06 UTC, dardorsh commented on source/catalog.html
>                        <div class="range-controls">
fixed

2021-01-14 07:23 UTC, dardorsh commented on source/catalog.html
>                    <div class="filter-setup__wrapper">
done

2021-01-14 11:41 UTC, merged