Добавляет адаптивный лого в svg формате и векторный спрайт
htmlacademy-adaptive/298063-pink-21 pull request #15
Opened 2021-01-16 17:46 UTC by dardorsh

2021-01-16 20:11 UTC, kosovych requested changes

2021-01-16 20:11 UTC, kosovych commented on source/catalog.html
>    </head>
иконку для like__button добавь и используй через спрайт

2021-01-16 20:11 UTC, kosovych commented on source/catalog.html
> +            </svg>
было правильно через picture

2021-01-16 20:11 UTC, kosovych commented on source/catalog.html
>    </head>
и желательно тоже все иконки с css вынести в спрайт

2021-01-17 10:25 UTC, dardorsh commented on source/catalog.html
>    </head>
Вынесла иконки в сss в спрайт, а они тоже не отображаются почему-то. Может инлайновый спрайт оставить?

2021-01-17 15:43 UTC, kosovych commented on source/catalog.html
>    </head>
забыла вынести в спрайт иконки для slider__button

2021-01-17 15:44 UTC, kosovych requested changes

2021-01-17 15:44 UTC, kosovych commented on source/catalog.html
> +    </object>
я так, понимаю он тут не нужен?

2021-01-17 15:55 UTC, dardorsh commented on source/catalog.html
>    </head>
> забыла вынести в спрайт иконки для slider__button

поправила

2021-01-17 15:56 UTC, dardorsh commented on source/catalog.html
> +    </object>
забыла убрать, fixed

2021-01-17 16:02 UTC, merged