Автоматизация проекта
htmlacademy-adaptive/298063-pink-21 pull request #16
Opened 2021-01-17 18:28 UTC by dardorsh

2021-01-17 20:38 UTC, kosovych requested changes

2021-01-17 20:38 UTC, kosovych commented on gulpfile.js
>  const sass = require("gulp-sass");
сборка должна запускаться командой `npm run build`

2021-01-17 20:38 UTC, kosovych commented on gulpfile.js
> +const webp = require("gulp-webp");
у тебя есть таска для создания webp, поэтому можно удалить с source

2021-01-17 20:38 UTC, kosovych commented on gulpfile.js
>  const sass = require("gulp-sass");
![image](https://user-images.githubusercontent.com/19348382/104855149-d227b380-5913-11eb-9181-b4caf2970e94.png)
в build попадает scss

2021-01-17 20:38 UTC, kosovych commented on gulpfile.js
>  const sass = require("gulp-sass");
в папке build должна быть папка css с скомпилированными и минифицированными стилевыми файлами (к странице должен быть подключён минифицированный файл);

2021-01-17 20:38 UTC, kosovych commented on gulpfile.js
>  const sass = require("gulp-sass");
![image](https://user-images.githubusercontent.com/19348382/104855186-fc797100-5913-11eb-8a1b-1e3d1c8e9840.png)
спрайт в build пустой

2021-01-17 20:38 UTC, kosovych commented on gulpfile.js
> +);
зачем в build запускать сервер?

2021-01-17 20:38 UTC, kosovych commented on gulpfile.js
> +}
у тебя нет такой папки для иконок. или собирай спрайт gulp'ом, или удали эту таску

2021-01-18 06:18 UTC, dardorsh commented on gulpfile.js
> +);
fixed

2021-01-18 06:20 UTC, dardorsh commented on gulpfile.js
>  const sass = require("gulp-sass");
fixed

2021-01-18 06:23 UTC, dardorsh commented on gulpfile.js
> +const webp = require("gulp-webp");
done

2021-01-18 06:37 UTC, dardorsh commented on gulpfile.js
>  const sass = require("gulp-sass");
fixed

2021-01-18 06:38 UTC, dardorsh commented on gulpfile.js
>  const sass = require("gulp-sass");
fixed

2021-01-18 07:38 UTC, dardorsh commented on gulpfile.js
> +}
done

2021-01-18 07:50 UTC, kosovych commented on gulpfile.js
>  const sass = require("gulp-sass");
@dardorsh есть только минифицированные стили, а просто скомпилированных - нет

2021-01-18 15:42 UTC, merged