Улучшает скорость загрузки
htmlacademy-adaptive/298063-pink-21 pull request #17
Opened 2021-01-18 17:17 UTC by dardorsh

2021-01-18 22:34 UTC, kosovych requested changes

2021-01-18 22:34 UTC, kosovych commented on source/css/style.css
>  @font-face {
добавь файл в гитигнор

2021-01-18 22:34 UTC, kosovych commented on source/form.html
> +          <a class="page-header__logo logo" href="index.html">
href="/"

2021-01-18 22:34 UTC, kosovych commented on source/css/style.css
> +  src: local("Open Sans Light"), local("OpenSans-Light"), url("../../fonts/opensanslight.woff2") format("woff2"), url("../../fonts/opensanslight.woff") format("woff"); }
путь к шрифту строй от папки css, а не фактического файла scss

2021-01-19 12:15 UTC, dardorsh commented on source/css/style.css
>  @font-face {
done

2021-01-19 12:23 UTC, dardorsh commented on source/css/style.css
> +  src: local("Open Sans Light"), local("OpenSans-Light"), url("../../fonts/opensanslight.woff2") format("woff2"), url("../../fonts/opensanslight.woff") format("woff"); }
fixed

2021-01-19 16:56 UTC, kosovych requested changes

2021-01-19 16:56 UTC, kosovych commented on .gitignore
> +css/
source/css/ => сделай коммит => удали папку => сделай коммит

2021-01-19 17:08 UTC, dardorsh commented on .gitignore
> +css/
done

2021-01-19 18:21 UTC, merged