Базовая стилизация index.html
htmlacademy-adaptive/298063-pink-21 pull request #5
Opened 2020-12-12 14:37 UTC by dardorsh

2020-12-12 21:30 UTC, kosovych requested changes
подключи локальные шрифты и проверь начертание заголовков

2020-12-12 21:30 UTC, kosovych commented on source/index.html
> +          <span class="advantages__title--bottom">Нам есть, что вам <br> предложить!</span>
проверь начертания шрифта

2020-12-12 21:30 UTC, kosovych commented on source/sass/style.scss
> -// Начните писать стили здесь
создай отдельный файл для подключения шрифтов и подключи их с папки

2020-12-12 21:30 UTC, kosovych commented on source/sass/blocks/pricing.scss
> +.prices-table__item {
заголовки столбцов апперкейсом должны быть

2020-12-12 21:30 UTC, kosovych commented on source/sass/blocks/contacts.scss
> +.contacts__title {
проверь начертание

2020-12-13 06:02 UTC, dardorsh commented on source/sass/style.scss
> -// Начните писать стили здесь
+

2020-12-13 06:28 UTC, dardorsh commented on source/index.html
> +          <span class="advantages__title--bottom">Нам есть, что вам <br> предложить!</span>
done

2020-12-13 06:31 UTC, dardorsh commented on source/sass/blocks/pricing.scss
> +.prices-table__item {
fixed

2020-12-13 06:33 UTC, dardorsh commented on source/sass/blocks/contacts.scss
> +.contacts__title {
done

2020-12-13 08:44 UTC, merged