Адаптивная сетка для form.html
htmlacademy-adaptive/298063-pink-21 pull request #9
Opened 2020-12-17 10:26 UTC by dardorsh

2020-12-17 20:09 UTC, kosovych requested changes

2020-12-17 20:09 UTC, kosovych commented on source/sass/blocks/survey.scss
>  @import "../sass/variables.scss";
не нужно импортировать переменные в каждый файл, достаточно в style.scss раньше всех подключить

2020-12-17 20:09 UTC, kosovych commented on source/sass/blocks/survey.scss
> +  @media (min-width: $desktop-width) {
почему $desktop-width 960рх?

2020-12-17 20:09 UTC, kosovych commented on source/form.html
> +          <img src="https://via.placeholder.com/150x150" width="145px" height="40px" alt="Логотип Pink">
в атрибутах width и height единицы измерения указывать не нужно

2020-12-17 20:09 UTC, kosovych commented on source/form.html
> +              <span class="competition__intro--hidden">Пожалуйста, заполните форму ниже:</span>
не по БЭМу (модификатор без элемента)

2020-12-17 20:09 UTC, kosovych requested changes

2020-12-17 20:09 UTC, kosovych commented on source/form.html
> +            <div class="survey__section--submit">
модификатор без элемента

2020-12-17 20:09 UTC, kosovych commented on source/form.html
> +                <span class="survey__legend--coloured">*</span> — обязательные поля
модификатор без элемента

2020-12-18 17:58 UTC, dardorsh commented on source/sass/blocks/survey.scss
> +  @media (min-width: $desktop-width) {
resolved

2020-12-18 17:58 UTC, dardorsh commented on source/sass/blocks/survey.scss
>  @import "../sass/variables.scss";
fixed

2020-12-18 18:14 UTC, dardorsh commented on source/form.html
> +          <img src="https://via.placeholder.com/150x150" width="145px" height="40px" alt="Логотип Pink">
fixed

2020-12-18 18:16 UTC, dardorsh commented on source/form.html
> +              <span class="competition__intro--hidden">Пожалуйста, заполните форму ниже:</span>
fixed

2020-12-18 18:18 UTC, dardorsh commented on source/form.html
> +            <div class="survey__section--submit">
fixed

2020-12-18 18:19 UTC, dardorsh commented on source/form.html
> +                <span class="survey__legend--coloured">*</span> — обязательные поля
fixed

2020-12-19 18:57 UTC, merged